### ISSUE TITLE
Add ability to specify project_name when creating jobs

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/ansible-collection-memsource#12]
When creating jobs on a memsource project, the project can currently only be specified with the project_uid.  It may be easier for some people to specify a project name to regex for.  

We would need to add a parameter for `project_name` [here](https://github.com/ansible/ansible-collection-memsource/blob/main/plugins/modules/memsource_job.py#L83-L90).  The tricky part is that there could be multiple projects that match the regex, so we would want to be sure to fail if there is more than one match.  The docs should recommend project_uid as being the most robust way to do it.

**Comment by adityamulik** [comment]
@rooftopcellist This issue has been fixed as per PR https://github.com/ansible/ansible-collection-memsource/pull/23 

Ref Doc: https://cloud.memsource.com/web/docs/api#operation/listProjects

Using listProject GET API request and passing the query paramter project name retrieves the recent most project despite having duplicate names. The user must ensure to enter the project_name string similar to the project_name which was used to create a project on Memsource.

**Comment by rooftopcellist** [comment]
Thanks @adityamulik !

We can close this now then.
