### ISSUE TITLE
Add ability to configure local pre_translations.sh script

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/ansible-collection-memsource#39]
Add the ability to specify a file local to the machine running the pre_translations role in order to not require committing the extraction script to the upstream codebase.  

Context: https://github.com/ansible/galaxy_ng/pull/1350#issuecomment-1266933726

**Comment by adityamulik** [comment]
Hello @rooftopcellist,

Thanks for the reported issue/ feature. 
I was thinking we can approach this issue to have script placed in the forked repository (e.g. adityamulik/galaxy_ng or any applicable repo which is being used to perform translation) of the main repo (e.g. ansible/galaxy_ng) which is supposed to be translated. 

At the main repo (ansible/galaxy_ng) would have the pre_translation.sh & post_translation.sh scripts added to .gitignore.

So when we proceed to begin running the ansible role (pre/ post translation), the script would read the pre/ post translation script from the forked repo (here in case adityamulik/galaxy_ng). 

When committing the files back, the scripts (pre/ post_translation) would be ignored while merging back on the PR. 
If this approach seems good, I have already opened a feature branch in my repo (adityamulik/ansible-collection-memsource) and would begin with the implementation.

As per above, we can proceed to move all scripts for rest of Ansible products to forked repository as per plan. 
Please advise if any further improvement or change can be advised, I will work on it similarly.

**Comment by adityamulik** [comment]
Ref: https://github.com/adityamulik/ansible-collection-memsource/tree/pre_translation_scripts_downstream

**Comment by rooftopcellist** [comment]
@adityamulik The fork idea is an interesting approach.  My reluctance there is that it assumes a single person will be doing the automation, and the script lives on their fork, so if they leave ACME company and delete their Github account... etc.  

Of course, the branch could live on the main app repo too (not a fork), but it still necessitates having a fork, and potentially having to periodically sync that fork to keep it up to date with the main branch.  

What do you think about being able to specify a custom `local_shell_script_path` as an parameter, which gets copied into the clone and executed just the same as we currently do it?  Here's a PR that does it for pre & post scripts:
* https://github.com/ansible/ansible-collection-memsource/pull/45

**Comment by rooftopcellist** [comment]
Resolved by: https://github.com/ansible/ansible-collection-memsource/pull/45
